version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: go_todo_persistence_db
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_DB=go_todo_persistence_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=pgadmin'